### ISSUE TITLE
Dan Hett’s Cyril Patterns website is non-existent

### ISSUE THREAD

**Issue by gguiomar** [cyrilcode/cyril#29]
Is there a mirror for the stuff that was on that website?

**Comment by danhett** [comment]
Oh! Man, you're right, I had no idea. 

I might have an archive somewhere, I made a lot of notes, I'll check when I get time and let you know.

**Comment by marcinbiegun** [comment]
@gguiomar @danhett I've found it under different address than the one given on medium.com site: http://cyrilpatterns-blog.tumblr.com

**Comment by darrenmothersele** [comment]
Thanks @marcinbiegun - I've updated the link on the website.
